version: '3'
services:
  frontend:
    build:
      context: ./frontend # Path to frontend Dockerfile
    ports:
      - "3000:3000"       # Maps frontend container's port 3000 to the host's port 3000
    depends_on:
      - backend            # Ensure backend starts before frontend

  backend:
    build:
      context: ./backend   # Path to backend Dockerfile
    ports:
      - "5000:5000"        # Maps backend container's port 5000 to the host's port 5000
    volumes:
      - ./backend:/usr/src/app # Syncs local backend files with the container for development
